# ********************************
# MFD Crossbow tracker backpack
# ********************************

[env:MFD_Crossbow_ESP8285_Backpack_via_UART]
extends = env_common_esp8285, mfd_crossbow_backpack_common
build_flags =
	${env_common_esp8285.build_flags}
	${mfd_crossbow_backpack_common.build_flags}
    -D PIN_BUTTON=0
    -D PIN_LED=16

[env:MFD_Crossbow_ESP8285_Backpack_via_WIFI]
extends = env:MFD_Crossbow_ESP8285_Backpack_via_UART

[env:MFD_Crossbow_ESP32_Backpack_via_UART]
extends = env_common_esp32, mfd_crossbow_backpack_common
build_flags =
	${env_common_esp32.build_flags}
	${mfd_crossbow_backpack_common.build_flags}
    -D PIN_BUTTON=0

[env:MFD_Crossbow_ESP32_Backpack_via_WIFI]
extends = env:MFD_Crossbow_ESP32_Backpack_via_UART

[env:MFD_Crossbow_HeltecWifiKit32_Backpack_via_UART]
extends = env_common_esp32, mfd_crossbow_backpack_common
board = heltec_wifi_kit_32
upload_port = COM8
upload_speed = 460800
monitor_speed = 115200
build_flags =
	${env_common_esp32.build_flags}
	${mfd_crossbow_backpack_common.build_flags}
    -D PIN_BUTTON=0
    -D PIN_LED=25
    -D OLED_SSD1306=1
    -D OLED_SDA=4
    -D OLED_SCL=15
    -D OLED_RST=16
    -D HELTEC_VEXT=21
    -D OLED_INVERT=1
lib_deps =
	${mfd_crossbow_backpack_common.lib_deps}
	olikraus/U8g2 @ ^2.35.30

[env:MFD_Crossbow_HeltecWifiKit32_Backpack_via_WIFI]
extends = env:MFD_Crossbow_HeltecWifiKit32_Backpack_via_UART

[env:MFD_Crossbow_ESP32_OLED_Backpack_via_UART]
extends = env_common_esp32, mfd_crossbow_backpack_common
monitor_speed = 115200
build_flags =
	${env_common_esp32.build_flags}
	${mfd_crossbow_backpack_common.build_flags}
    -D PIN_BUTTON=0
    -D PIN_LED=2
    -D OLED_SSD1306=1
    -D OLED_SDA=21
    -D OLED_SCL=22
lib_deps =
	${mfd_crossbow_backpack_common.lib_deps}
	olikraus/U8g2 @ ^2.35.30

[env:MFD_Crossbow_ESP32_OLED_Backpack_via_WIFI]
extends = env:MFD_Crossbow_ESP32_OLED_Backpack_via_UART

[env:MFD_Crossbow_ESP32C3_Backpack_via_UART]
extends = env_common_esp32c3, mfd_crossbow_backpack_common
build_flags =
	${env_common_esp32c3.build_flags}
	${mfd_crossbow_backpack_common.build_flags}
    -D PIN_BUTTON=9

[env:MFD_Crossbow_ESP32C3_Backpack_via_WIFI]
extends = env:MFD_Crossbow_ESP32C3_Backpack_via_UART

[env:MFD_Crossbow_ESP32S3_Backpack_via_UART]
extends = env_common_esp32s3, mfd_crossbow_backpack_common
build_flags =
	${env_common_esp32s3.build_flags}
	${mfd_crossbow_backpack_common.build_flags}
    -D PIN_BUTTON=0

[env:MFD_Crossbow_ESP32S3_Backpack_via_WIFI]
extends = env:MFD_Crossbow_ESP32S3_Backpack_via_UART
